---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
library(ggplot2)
activity <- read.csv("activity.csv")

library(ggplot2)
library(dplyr)
Sys.setlocale("LC_TIME", "English")

str(activity)
```


## What is mean total number of steps taken per day?

```{r}

# 1. Calculate the total number of steps taken per day
StepsPerDay <- aggregate(activity$steps, list(activity$date), FUN=sum)
colnames(StepsPerDay) <- c("Date", "Steps")
StepsPerDay

# 2. Make a histogram of the total number of steps taken each day
g <- ggplot(StepsPerDay, aes(Steps))
g+geom_histogram(boundary=0, binwidth=2500, col="darkgreen", fill="lightgreen")+ggtitle("Histogram of steps per day")+xlab("Steps")+ylab("Frequency")+theme(plot.title = element_text(face="bold", size=12))+scale_x_continuous(breaks=seq(0,25000,2500))+scale_y_continuous(breaks=seq(0,18,2))

# 3. Calculate and report the mean and median of the total number of steps taken per day

# Mean
mean(StepsPerDay$Steps, na.rm=TRUE)

#Median
median(StepsPerDay$Steps, na.rm=TRUE)
```



## What is the average daily activity pattern?

```{r}

# 1. Make a time series plot
StepsPerTime <- aggregate(steps~interval,data=activity,FUN=mean,na.action=na.omit)
# variable time (more comprensible for the graph axis)
StepsPerTime$time <- StepsPerTime$interval/100
# draw the line plot
h <- ggplot(StepsPerTime, aes(time, steps))
h+geom_line(col="blue")+ggtitle("Average steps per time interval")+xlab("Time")+ylab("Steps")+theme(plot.title = element_text(face="bold", size=11))

# 2. Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?

# table for dplyr
ST <- tbl_df(StepsPerTime)
# find the column
ST %>% select(time, steps) %>% filter(steps==max(ST$steps))
```

## Imputing missing values
```{r}

# 1. Total number of missing values in the dataset (i.e. the total number of rows with NAs)

# table for dplyr
ACT <- tbl_df(activity)
# find the column
ACT %>% filter(is.na(steps)) %>% summarize(missing_values = n())

# 2. Fill in all of the missing values in the dataset.

# values without NA are imputed in a new column
activity$CompleteSteps <- ifelse(is.na(activity$steps), round(StepsPerTime$steps[match(activity$interval, StepsPerTime$interval)],0), activity$steps)

# 3. Create a new dataset that is equal to the original dataset but with the missing data filled in.

# new dataset activityFull
activityFull <- data.frame(steps=activity$CompleteSteps, interval=activity$interval, date=activity$date)
# see first 10 values of the new dataset
head(activityFull, n=10)

# 4.  Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. 

# prepare data
StepsPerDayFull <- aggregate(activityFull$steps, list(activityFull$date), FUN=sum)
colnames(StepsPerDayFull) <- c("Date", "Steps")
# draw the histogram
g <- ggplot(StepsPerDayFull, aes(Steps))
g+geom_histogram(boundary=0, binwidth=2500, col="darkblue", fill="lightblue")+ggtitle("Histogram of steps per day")+xlab("Steps")+ylab("Frequency")+theme(plot.title = element_text(face="bold", size=12))+scale_x_continuous(breaks=seq(0,25000,2500))+scale_y_continuous(breaks=seq(0,26,2))

# Mean
mean(StepsPerDayFull$Steps)

#Median
median(StepsPerDayFull$Steps)

```



## Are there differences in activity patterns between weekdays and weekends?
